### ISSUE TITLE
Afegir camp a la taula de BD d'Evidència que sigui la propietat del json "login.properties.sha256"

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/evidenciesib#33]
Afegir camp a la taula de BD d'Evidència que sigui la propietat del json "login.properties.sha256"

![imatge](https://github.com/GovernIB/evidenciesib/assets/17084256/07a32feb-593f-483a-9ba3-6e2a9d26b7c2)

**Comment by kitanibaladmin** [comment]
Solucionat
